# -*- coding: utf-8 -*-
"""VNDBのタグ・キャラ属性の日本語訳。乙女ゲームで頻出する語を収録。
未収録の語は英語のまま出力される（欠落ではなく未訳）。
"""

TAG_JA = {
    "Otome Game": "乙女ゲーム", "Female Protagonist": "女性主人公", "ADV": "ADV形式",
    "No Sexual Content": "性的描写なし", "Protagonist with a Face": "主人公の顔が見える",
    "Nameable Protagonist": "主人公の名前変更可", "Multiple Endings": "マルチエンディング",
    "Romance": "恋愛", "Hero with Glasses": "眼鏡の攻略対象", "Adult Hero": "成人の攻略対象",
    "High School Student Protagonist": "高校生の主人公",
    "Protagonist's Childhood Friend as a Hero": "幼馴染が攻略対象",
    "Adult Protagonist": "成人の主人公", "More Than Seven Endings": "エンディング8種以上",
    "Voiced Default Name": "デフォルト名を音声で呼ぶ", "Only a Single Hero": "攻略対象は1人のみ",
    "Only Adult Heroes": "攻略対象は全員成人", "Side Portraits": "立ち絵が横向き",
    "Yandere Hero": "ヤンデレの攻略対象", "Sexual Content": "性的描写あり", "Fantasy": "ファンタジー",
    "Modern Day Japan": "現代日本", "High School": "高校が舞台", "Student Hero": "学生の攻略対象",
    "Bad Ending(s)": "バッドエンドあり", "Protagonist with a Sprite": "主人公に立ち絵あり",
    "Shota Hero": "ショタの攻略対象", "Other Perspectives": "他視点パート",
    "Unlockable Routes": "解放式ルート", "Correct Choice Indicator": "正解選択肢の表示",
    "Bad Endings with Story": "物語のあるバッドエンド", "Tsundere Hero": "ツンデレの攻略対象",
    "Strong Female Protagonist": "芯の強い女性主人公", "White Haired Hero": "白髪の攻略対象",
    "Comedy": "コメディ", "Protagonist with Voice Acting": "主人公にボイスあり",
    "More Than Seven Heroes": "攻略対象8人以上", "Teacher Hero": "教師の攻略対象",
    "Ending List": "エンディング一覧機能", "Bonus Side Stories": "おまけシナリオ",
    "Oyaji Hero": "オヤジ系の攻略対象", "Music Recollection": "音楽鑑賞モード",
    "Photographic Backgrounds": "実写背景", "Lip Sync": "口パク同期",
    "Built-in Encyclopedia": "用語辞典搭載", "Under the Same Roof": "同居",
    "Map Movement": "マップ移動", "Unlockable Bonus Content": "解放式おまけ要素",
    "High School Student Hero": "高校生の攻略対象", "Drama": "ドラマ", "Bloody Scenes": "流血描写",
    "Branching Plot": "分岐する物語", "Normal Scene Recollection": "シーン回想",
    "Long Common Route": "共通ルートが長い", "Hero with a Sword": "剣を持つ攻略対象",
    "Brief NVL Scenes": "一部NVL形式", "Portrait Orientation": "縦画面",
    "Microtransactions": "課金要素", "Past Japan": "過去の日本", "Royal Hero": "王族の攻略対象",
    "Wealthy Hero": "富裕層の攻略対象", "Chosen Choices Marking": "既読選択肢の表示",
    "Backlog Jump": "バックログジャンプ", "Death of Hero": "攻略対象の死",
    "Sexual Innuendo": "性的な暗示", "Female Friend": "女友達",
    "Character Profiles": "キャラ紹介機能", "Fighting Hero": "戦う攻略対象",
    "Marriage Ending": "結婚エンド", "Multiple Route Mystery": "複数ルートで解ける謎",
    "Life and Death Drama": "生死を扱う物語", "Date Display": "日付表示",
    "Lots of Choices": "選択肢が多い", "Hero with Eyepatch": "眼帯の攻略対象",
    "Hero with Beauty Mark": "ほくろのある攻略対象", "Flirtatious Hero": "軽薄な攻略対象",
    "Relationship Chart": "相関図", "Varied Title Screens": "タイトル画面が変化",
    "Fan-fiction": "二次創作", "Hero Based on Real Person": "実在人物がモデルの攻略対象",
    "Enforced Playing Order": "攻略順の強制", "Magic": "魔法", "Mystery": "ミステリー",
    "Dark Skinned Hero": "褐色肌の攻略対象", "May-December Romance": "年の差恋愛",
    "Amnesia": "記憶喪失", "Japanese Mythology": "日本神話", "Flashback": "回想",
    "Knight Hero": "騎士の攻略対象", "Ponytail Hero": "ポニーテールの攻略対象",
    "One True End": "真エンドが1つ", "Protagonist's Senpai as a Hero": "先輩が攻略対象",
    "Colored Name-tags": "名前の色分け", "Princess Protagonist": "姫の主人公",
    "Demon Hero": "鬼・魔族の攻略対象", "Butler Hero": "執事の攻略対象",
    "Fast Mini-games": "短いミニゲーム", "Twin Brothers as Heroes": "双子の兄弟が攻略対象",
    "Kinetic Novel": "一本道（選択肢なし）", "Vampire Hero": "吸血鬼の攻略対象", "War": "戦争",
    "Fictional World": "架空世界", "Fighting Protagonist": "戦う主人公",
    "Orphan Protagonist": "孤児の主人公", "Kuudere Hero": "クーデレの攻略対象",
    "Protagonist's Non-blood-related Brother as a Hero": "義兄弟が攻略対象",
    "Multiple Protagonists": "主人公が複数", "Confinement": "監禁",
    "Past Setting in a Fictional World": "架空世界の過去", "Noble Hero": "貴族の攻略対象",
    "University Student Hero": "大学生の攻略対象", "Musician Hero": "音楽家の攻略対象",
    "Unlockable Hero(ine)": "解放式の攻略対象", "Time Travel": "タイムトラベル",
    "Non-human Hero": "人外の攻略対象", "Ponytail Protagonist": "ポニーテールの主人公",
    "Hero(ine) Selection": "攻略対象の選択制", "Sword Combat": "剣戟",
    "Western-style Manor": "洋館", "University Student Protagonist": "大学生の主人公",
    "Homicide": "殺人", "Horror": "ホラー", "Foreigner Hero": "外国人の攻略対象",
    "Slice of Life": "日常", "Villainous Hero": "悪役の攻略対象",
    "Medical Doctor Hero": "医師の攻略対象", "Death of Protagonist": "主人公の死",
    "Reincarnation": "転生", "Student Protagonist": "学生の主人公",
    "Jump to Next Choice": "次の選択肢へジャンプ",
    "NVL": "NVL形式", "Halloween": "ハロウィン", "The Holiday Season": "クリスマス・年末",
    "Scenario Selection": "シナリオ選択式", "Protagonist's Kouhai as a Hero": "後輩が攻略対象",
    "Protagonist's Side Image Toggle": "主人公立ち絵の表示切替",
    "Protagonist from a Different World": "異世界から来た主人公",
    "Valentine's Day": "バレンタイン", "Few Event CGs": "イベントCGが少ない",
    "Changeable Font": "フォント変更可", "Fairy Tale": "おとぎ話", "Hero in Kimono": "着物の攻略対象",
    "Simulation Game": "シミュレーション", "RPG": "RPG要素",
    "Protagonist's Brother as a Hero": "兄弟が攻略対象", "Summer": "夏",
    "Cheerful Hero": "明るい攻略対象", "Few Choices": "選択肢が少ない",
    "Soldier Hero": "軍人の攻略対象", "Protagonist in Relationship": "主人公に恋人がいる",
    "Ending Scene Recollection": "エンディング回想", "Super Deformed CGs": "デフォルメCG",
    "Loli Protagonist": "幼い主人公", "Completion Status Indicator": "達成率表示",
    "Kemonomimi Hero": "けものみみの攻略対象", "April Fool's": "エイプリルフール",
    "Idol Hero": "アイドルの攻略対象", "Ojousama Protagonist": "お嬢様の主人公",
    "Cafe": "カフェ", "Literary Adaptation": "文学作品が原作",
    "Unoriginal Soundtrack": "既製曲の使用", "Hero Based on a Fictional Person": "架空人物がモデルの攻略対象",
    "Donkan Protagonist": "鈍感な主人公", "Unlockable Choices": "解放式選択肢",
    "Polite Formal Hero": "敬語の攻略対象", "Built-in Walkthrough": "攻略ヒント搭載",
    "Mage Hero": "魔法使いの攻略対象", "Hero with Eye Covering Hairstyle": "目が隠れる髪の攻略対象",
    "Twin Tail Protagonist": "ツインテールの主人公", "Prince Hero": "王子の攻略対象",
    "Shinsengumi": "新選組", "Samurai Hero": "侍の攻略対象", "Bakumatsu Era": "幕末",
    "Edo Era": "江戸時代", "Rebellion": "反乱",
    "Has Window Transparency Setting": "ウィンドウ透過設定", "Unique Routes": "ルートごとに展開が異なる",
    "Proactive Protagonist": "積極的な主人公", "Read Text Marking": "既読テキストの表示",
    "Restart from Chapter Index": "章から再開できる", "Shota Support Character": "ショタのサブキャラ",
    "Skip Scenes": "シーンスキップ", "Leader Hero": "リーダー気質の攻略対象",
    "Timed Choices": "制限時間つき選択肢", "Gauge Display": "好感度ゲージ表示",
    "Location Display": "場所の表示", "Orphan Hero": "孤児の攻略対象",
    "Playboy Hero": "遊び人の攻略対象", "Protagonist with Partial Voice Acting": "主人公が部分ボイス",
    "Episodic Story": "エピソード形式", "Kissing Scene": "キスシーンあり",
    "Police Officer Hero": "警察官の攻略対象", "Romancing a Family": "兄弟が攻略対象",
    "Combat Capable Friends": "戦える仲間", "Game Over": "ゲームオーバーあり",
    "Interactive Touching Game": "タッチ操作のミニゲーム", "Unlockable Epilogue": "解放式エピローグ",
    "Discrimination": "差別を扱う", "Based on a Manga": "漫画が原作",
    "Delinquent Hero": "不良の攻略対象", "Friendship Ending": "友情エンド",
    "High Amount of Bad Endings": "バッドエンドが多い", "Politics": "政治を扱う",
    "Bodyguard Hero": "ボディガードの攻略対象", "Early Branching Plot": "早い段階で分岐",
    "Raising Simulation": "育成シミュレーション", "Reverse Trap Protagonist": "男装の主人公",
    "Student Council President Hero": "生徒会長の攻略対象", "Student-Teacher Romance": "教師と生徒の恋愛",
    "Athlete Hero": "運動部の攻略対象", "Catboy Hero": "猫耳の攻略対象",
    "Dating Simulation": "恋愛シミュレーション",
    "Different Love Interest(s) Per Protagonist": "主人公ごとに攻略対象が違う",
    "Floating Textbox": "浮遊型テキストボックス", "Inter-class Romance": "身分差の恋愛",
    "Unlockable Event": "解放式イベント", "Achievements": "実績・トロフィー", "Friendship": "友情",
    "Hero with Gothic Look": "ゴシックな装いの攻略対象", "Love Overcomes All": "愛がすべてを超える",
    "Protagonist Selection": "主人公を選べる", "Protagonist's Cousin as a Hero": "いとこが攻略対象",
    "Short Common Route": "共通ルートが短い", "Smoker Hero": "喫煙する攻略対象",
    "Writer Hero": "作家の攻略対象", "Mischievous Hero": "いたずら好きの攻略対象",
    "Multiple Common Routes": "共通ルートが複数", "Protagonist's Boss as Hero": "上司が攻略対象",
    "Protagonist's Brother as a Support Character": "兄弟がサブキャラ", "Youkai": "妖怪",
    "Based on an Anime": "アニメが原作", "Musician Protagonist": "音楽家の主人公",
    "Only Good Endings": "グッドエンドのみ", "Otaku Hero": "オタクの攻略対象",
    "Protagonist Based on a Fictional Person": "架空人物がモデルの主人公",
    "Sengoku Period": "戦国時代", "Varying Ending Songs": "エンディング曲が複数",
    "Youkai Hero": "妖怪の攻略対象", "100% Completion Bonus": "全クリア特典",
    "Actor Hero": "俳優の攻略対象", "Co-worker Hero": "同僚が攻略対象",
    "Friendship Route": "友情ルート", "Interracial/interspecies Romance": "異種族間の恋愛",
    "Love Triangle": "三角関係", "Magic School": "魔法学校", "Shinobi Hero": "忍者の攻略対象",
    "Slice of Life Comedy": "日常コメディ", "Action": "アクション",
    "Charming Protagonist": "魅力的な主人公", "Choices with 4 or More Options": "4択以上の選択肢",
    "Dark Fantasy": "ダークファンタジー", "Deredere Hero": "デレデレの攻略対象",
    "Genius Hero": "天才の攻略対象", "Group of Friends": "仲間グループ",
    "Hero with Heterochromia": "オッドアイの攻略対象", "Island": "島が舞台", "Madness": "狂気",
    "Magic/ESP Combat": "魔法・超能力バトル", "Male Protagonist": "男性主人公",
    "Musical Themes": "音楽が題材", "Oni Hero": "鬼の攻略対象", "Rhythm Game": "リズムゲーム",
    "Sadist Hero": "サドの攻略対象", "Science Fiction": "SF", "Sickly Hero": "病弱な攻略対象",
    "Suspense": "サスペンス", "Sword Wielding Protagonist": "剣を使う主人公",
    "Vertically Oriented Text": "縦書きテキスト", "Winter": "冬",
    "Alternate Dimensions": "異世界・並行世界", "Androgynous Hero": "中性的な攻略対象",
    "Both Male and Female Love Interests": "男女どちらも攻略可能", "Crime": "犯罪を扱う",
    "Deities": "神が登場", "Medieval Fantasy": "中世ファンタジー",
    "Musical Environment": "音楽が身近な舞台", "Protagonist's Fiance as a Hero": "婚約者が攻略対象",
    "Slice of Life Drama": "日常ドラマ", "Unlockable Gallery": "解放式ギャラリー",
    "Utsuge": "鬱ゲー", "Assassin Hero": "暗殺者の攻略対象", "Brother/Sister Romance": "義兄妹の恋愛",
    "Butler Support Character": "執事のサブキャラ", "Descriptions of Violence": "暴力描写",
    "Food Discussions": "食べ物の話題", "Hero with Sexual Experience": "経験のある攻略対象",
    "Hero with Tattoo": "タトゥーのある攻略対象", "Interactive Adventure Game": "探索型アドベンチャー",
    "Model Hero": "モデルの攻略対象", "Modern Day": "現代", "Modern Day Tokyo": "現代の東京",
    "Murder Mystery": "殺人ミステリー", "Plants & Flowers": "花・植物",
    "Playtime Counter": "プレイ時間表示", "Priest Hero": "聖職者の攻略対象",
}

TRAIT_GROUP_JA = {
    "Hair": "髪", "Eyes": "瞳", "Body": "外見", "Clothes": "服装",
    "Personality": "性格", "Role": "役柄", "Engages in": "行動",
    "Subject of": "境遇", "Items": "持ち物",
}

TRAIT_JA = {
    "Hair > Short": "短髪", "Hair > Long": "長髪", "Hair > Brown": "茶髪", "Hair > Black": "黒髪",
    "Hair > Blond": "金髪", "Hair > Grey": "灰髪", "Hair > White": "白髪", "Hair > Blue": "青髪",
    "Hair > Red": "赤髪", "Hair > Violet": "紫髪", "Hair > Green": "緑髪", "Hair > Pink": "ピンク髪",
    "Hair > Orange": "オレンジ髪", "Hair > Multicolored": "多色の髪",
    "Hair > Shoulder-length": "肩までの髪", "Hair > Waist Length+": "腰までの髪",
    "Hair > Ponytail": "ポニーテール", "Hair > Straight": "ストレート", "Hair > Wavy": "ウェーブ",
    "Hair > Spiky": "逆立った髪", "Hair > Spiky Bangs": "尖った前髪", "Hair > V Bangs": "V字前髪",
    "Hair > Parted to Side": "横分け", "Hair > Parted in Middle": "中分け",
    "Hair > Curtained": "カーテン前髪", "Hair > Shaggy": "無造作ヘア",
    "Hair > Eye Covering": "目が隠れる髪", "Hair > Sidehair": "サイドヘア",
    "Eyes > Brown": "茶色の瞳", "Eyes > Blue": "青い瞳", "Eyes > Green": "緑の瞳",
    "Eyes > Amber": "琥珀色の瞳", "Eyes > Violet": "紫の瞳", "Eyes > Red": "赤い瞳",
    "Eyes > Black": "黒い瞳", "Eyes > Grey": "灰色の瞳", "Eyes > Pink": "ピンクの瞳",
    "Eyes > Hosome": "細目", "Eyes > Tareme": "たれ目", "Eyes > Tsurime": "つり目",
    "Body > Young-adult": "青年", "Body > Teen": "十代", "Body > Adult": "成人",
    "Body > Kid": "子ども", "Body > Pale": "色白", "Body > Olive": "褐色肌",
    "Body > Slim": "細身", "Body > Mole": "ほくろ", "Body > Kemonomimi": "けものみみ",
    "Body > Younger Appearance": "実年齢より幼い外見",
    "Clothes > School Uniform": "制服", "Clothes > Glasses": "眼鏡", "Clothes > Kimono": "着物",
    "Clothes > Suit": "スーツ", "Clothes > Shirt": "シャツ", "Clothes > Trousers": "ズボン",
    "Clothes > Necktie": "ネクタイ", "Clothes > Belt": "ベルト", "Clothes > Earrings": "ピアス",
    "Clothes > Gloves": "手袋", "Clothes > Vest": "ベスト", "Clothes > Jacket": "ジャケット",
    "Clothes > Blazer": "ブレザー", "Clothes > Coat": "コート", "Clothes > Cape": "マント",
    "Clothes > Dress": "ドレス", "Clothes > Boots": "ブーツ", "Clothes > Scarf": "マフラー",
    "Clothes > Cravat": "クラヴァット", "Clothes > Necklace": "ネックレス",
    "Clothes > Pendant Necklace": "ペンダント", "Clothes > Hairpin": "ヘアピン",
    "Personality > Kind": "優しい", "Personality > Friendly": "親しみやすい",
    "Personality > Mysterious": "謎めいた", "Personality > Serious": "真面目",
    "Personality > Refined": "上品", "Personality > Smart": "頭が良い",
    "Personality > Protective": "過保護", "Personality > Loyal": "忠実",
    "Personality > Stoic": "動じない", "Personality > Relaxed": "おっとり",
    "Personality > Hard Worker": "努力家", "Personality > Energetic": "元気",
    "Personality > Blunt": "無愛想", "Personality > Yandere": "ヤンデレ",
    "Personality > Tsundere": "ツンデレ", "Personality > Stubborn": "頑固",
    "Personality > Honest": "正直", "Personality > Reserved": "控えめ",
    "Personality > Confident": "自信家", "Personality > Taciturn": "無口",
    "Personality > Proactive": "積極的", "Personality > Arrogant": "傲慢",
    "Personality > Sharp-tongued": "毒舌",
    "Personality > Ore": "一人称「俺」", "Personality > Boku": "一人称「僕」",
    "Personality > Watashi": "一人称「私」",
    "Role > High School Student": "高校生", "Role > University Student": "大学生",
    "Role > Classmate": "同級生", "Role > Senpai": "先輩", "Role > Teacher": "教師",
    "Role > Childhood Friend": "幼馴染", "Role > Friend": "友人",
    "Role > Older Brother": "兄", "Role > Younger Brother": "弟",
    "Role > Twin Brother": "双子の兄弟", "Role > Father": "父親", "Role > Orphan": "孤児",
    "Role > Noble": "貴族", "Role > Prince": "王子", "Role > Wealthy": "裕福",
    "Role > Popular": "人気者", "Role > Antagonist": "敵役", "Role > Magician": "魔法使い",
    "Role > Nameable": "名前変更可", "Role > Based on a Real Person": "実在人物がモデル",
    "Role > Based on a Fictional Character": "架空人物がモデル",
    "Engages in > Fighting": "戦闘", "Engages in > Teasing": "からかう",
    "Engages in > Cooking": "料理", "Engages in > Flirting": "口説く",
    "Engages in > Murder": "殺人",
    "Items > Sword": "剣", "Items > Katana": "刀",
    "Subject of > Grief": "喪失・悲嘆", "Subject of > Death": "死",
    "Subject of > Confinement": "監禁される", "Subject of > Guilt": "罪悪感",
    "Role > Middle School Student": "中学生", "Role > Samurai": "侍", "Role > Kouhai": "後輩",
    "Role > Student": "学生", "Role > Knight": "騎士",
    "Body > Tall": "長身", "Body > Muscular": "筋肉質", "Body > Tattoo": "タトゥー",
    "Body > Androgynous": "中性的", "Body > Pointed Ears": "尖った耳",
    "Personality > Carefree": "気楽", "Personality > Strict": "厳格",
    "Personality > Cheerful": "明るい", "Personality > Womanizer": "女好き",
    "Personality > Outgoing": "社交的", "Personality > Mature": "大人びた",
    "Personality > Rude": "無礼", "Personality > Mischievous": "いたずら好き",
    "Personality > Naive": "純朴", "Personality > Short-tempered": "短気",
    "Personality > Sweets Lover": "甘い物好き",
    "Clothes > Hakama": "袴", "Clothes > Headband": "ヘアバンド",
    "Clothes > Ribbon Tie": "リボンタイ", "Clothes > Hat": "帽子",
    "Clothes > Choker": "チョーカー", "Clothes > Bracelet": "ブレスレット",
    "Clothes > Formal Shirt": "ドレスシャツ", "Clothes > Hoodie": "パーカー",
    "Clothes > Dress Shoes": "革靴", "Clothes > Decorative Belt": "装飾ベルト",
    "Clothes > Pendant Earrings": "垂れ下がるピアス", "Clothes > Knee-high Boots": "ニーハイブーツ",
    "Clothes > Ribbon Hair Tie": "リボンの髪飾り",
    "Hair > Blunt Bangs": "ぱっつん前髪", "Hair > Bob Cut": "ボブ", "Hair > Twin Tails": "ツインテール",
    "Hair > Ahoge": "アホ毛", "Hair > No Bangs": "前髪なし", "Hair > Braid": "三つ編み",
    "Eyes > Teal": "青緑の瞳", "Eyes > Cyan": "水色の瞳",
    "Engages in > Tennis": "テニス", "Engages in > Drinking": "飲酒",
    "Subject of > Teasing": "からかわれる",
    "Personality > Optimist": "楽天的", "Personality > Hotblooded": "熱血",
    "Personality > Selfish": "自分勝手", "Personality > Genius": "天才",
    "Personality > Pragmatic": "現実的", "Personality > Loner": "一匹狼",
    "Personality > Opposite Gender Voiced": "異性が声を担当",
    "Personality > Charismatic": "カリスマ", "Personality > Eccentric": "変わり者",
    "Personality > Honorable": "高潔", "Personality > Cold-hearted": "冷淡",
    "Personality > Shy": "内気", "Personality > Kuudere": "クーデレ",
    "Personality > Cruel": "残酷", "Personality > Emotional": "感情的",
    "Personality > Curious": "好奇心旺盛", "Personality > Food Lover": "食いしん坊",
    "Personality > Insightful": "洞察力がある", "Personality > Ore-sama": "一人称「俺様」",
    "Personality > Funny": "面白い", "Personality > Lazy": "怠け者",
    "Personality > Observant": "観察眼がある", "Personality > Brave": "勇敢",
    "Personality > Secretive": "秘密主義", "Personality > Airhead": "天然",
    "Personality > Sly": "狡猾", "Personality > Timid": "臆病",
    "Personality > Antisocial": "非社交的", "Personality > Altruistic": "献身的",
    "Personality > Cautious": "慎重", "Personality > Strange": "風変わり",
    "Personality > Competitive": "負けず嫌い", "Personality > Low Self-esteem": "自己評価が低い",
    "Personality > Immature": "幼稚", "Personality > Wise": "賢明",
    "Personality > Distrustful": "疑り深い", "Personality > Talkative": "おしゃべり",
    "Personality > Docile": "従順", "Personality > Whimsical": "気まぐれ",
    "Personality > Cynic": "皮肉屋", "Personality > Bookworm": "本好き",
    "Personality > Assertive": "自己主張が強い", "Personality > Ambitious": "野心的",
    "Personality > Violent": "暴力的", "Personality > Atashi": "一人称「あたし」",
    "Personality > Idiot": "おバカ", "Personality > Sleepyhead": "寝坊助",
    "Personality > Effeminate": "女性的", "Personality > Humble": "謙虚",
    "Personality > Narcissist": "ナルシスト", "Personality > Kansai-ben": "関西弁",
    "Personality > Moody": "気分屋", "Personality > Possessive": "独占欲が強い",
    "Body > Makeup": "化粧", "Body > Scar": "傷跡", "Body > Male Cleavage": "胸元の開いた服",
    "Body > Old": "高齢", "Body > Short": "小柄", "Body > Nail Polish": "ネイル",
    "Body > Fang": "八重歯",
    "Hair > Slicked Back": "オールバック", "Hair > Goatee": "顎ひげ",
    "Hair > Moustache": "口ひげ", "Hair > Bun": "お団子ヘア", "Hair > Claret": "赤紫の髪",
    "Hair > Cyan": "水色の髪", "Hair > Beard": "ひげ", "Hair > Teal": "青緑の髪",
    "Hair > Ringlet": "巻き毛", "Hair > Stubble": "無精ひげ",
    "Hair > Short Bangs": "短い前髪", "Hair > Tiny Braid": "細い三つ編み",
    "Hair > Side Tail": "サイドテール",
    "Eyes > Itome": "糸目", "Eyes > Garnet": "ガーネットの瞳",
    "Eyes > Heterochromia": "オッドアイ", "Eyes > Sanpaku Eyes": "三白眼",
    "Eyes > Hidden": "目元が隠れている",
    "Clothes > Eyepatch": "眼帯", "Clothes > Hair Tie": "髪留め", "Clothes > Shorts": "ショートパンツ",
    "Clothes > Lab Coat": "白衣", "Clothes > Hair Flower": "髪飾りの花", "Clothes > Ring": "指輪",
    "Clothes > Chain Jewellery": "チェーンアクセサリー", "Clothes > Sweater": "セーター",
    "Clothes > Cloak": "マント", "Clothes > T-shirt": "Tシャツ", "Clothes > Bandages": "包帯",
    "Clothes > Hood": "フード", "Clothes > Hair Ribbon": "髪のリボン",
    "Clothes > Sunglasses": "サングラス", "Clothes > Suspenders": "サスペンダー",
    "Clothes > Fingerless Gloves": "指ぬきグローブ", "Clothes > Coat Cape": "ケープコート",
    "Clothes > Fur Trim": "ファー付き", "Clothes > Cardigan": "カーディガン",
    "Clothes > Headphones": "ヘッドホン", "Clothes > Clothing with Ribbons": "リボン付きの服",
    "Clothes > Mask": "仮面", "Clothes > Collar": "首輪", "Clothes > Crop Top": "へそ出しトップス",
    "Clothes > Jeans": "ジーンズ", "Clothes > Uniform": "制服", "Clothes > Bandanna": "バンダナ",
    "Clothes > Brooch": "ブローチ", "Clothes > Bow Tie": "蝶ネクタイ",
    "Clothes > Knee-high Socks": "ニーハイソックス", "Clothes > Loafers": "ローファー",
    "Clothes > Military Uniform": "軍服", "Clothes > Skirt": "スカート",
    "Clothes > Tank Top": "タンクトップ", "Clothes > Gothic": "ゴシック",
    "Clothes > Robe": "ローブ", "Clothes > Sailor School Uniform": "セーラー服",
    "Clothes > Sports Shoes": "スニーカー",
    "Role > Younger Sister": "妹", "Role > Rival": "ライバル", "Role > Executive": "重役",
    "Role > Medical Doctor": "医師", "Role > Pet Owner": "ペットを飼っている",
    "Role > Bodyguard": "ボディガード", "Role > Shopkeeper": "店主", "Role > Soldier": "兵士",
    "Role > Older Sister": "姉", "Role > Princess": "姫", "Role > Cousin": "いとこ",
    "Role > Famous": "有名人", "Role > Son": "息子",
    "Role > Student Council President": "生徒会長", "Role > Commander": "指揮官",
    "Role > Musician": "音楽家", "Role > Management": "管理職", "Role > Cat": "猫",
    "Role > Daughter": "娘", "Role > Half-Japanese": "日本人とのハーフ", "Role > Mother": "母親",
    "Role > Onzoushi": "御曹司", "Role > Coworker": "同僚", "Role > Tsukkomi": "ツッコミ役",
    "Role > Honor Student": "優等生", "Role > Researcher": "研究者", "Role > Delinquent": "不良",
    "Role > Ojousama": "お嬢様", "Role > Police": "警察官", "Role > Actor": "俳優",
    "Role > Idol": "アイドル", "Role > King": "王",
    "Engages in > Cross-dressing": "女装・男装", "Engages in > Reading": "読書",
    "Engages in > Smoking": "喫煙", "Engages in > Planning": "策略を巡らす",
    "Engages in > Shapeshifting": "姿を変える", "Engages in > Cleaning": "掃除",
    "Engages in > Investigation": "捜査", "Engages in > Sarcasm": "皮肉を言う",
    "Engages in > Swordsmanship": "剣術",
    "Items > Handgun": "拳銃",
    "Subject of > Flirting": "口説かれる", "Subject of > Amnesia": "記憶を失う",
}
