# -*- coding: utf-8 -*-
"""VNDBのタグ・キャラ属性の日本語訳。乙女ゲームで頻出する語を収録。
未収録の語は英語のまま出力される（欠落ではなく未訳）。
"""

TAG_JA = {
    "Otome Game": "乙女ゲーム", "Female Protagonist": "女性主人公", "ADV": "ADV形式",
    "No Sexual Content": "性的描写なし", "Protagonist with a Face": "主人公の顔が見える",
    "Nameable Protagonist": "主人公の名前変更可", "Multiple Endings": "マルチエンディング",
    "Romance": "恋愛", "Hero with Glasses": "眼鏡の攻略対象", "Adult Hero": "成人の攻略対象",
    "High School Student Protagonist": "高校生の主人公",
    "Protagonist's Childhood Friend as a Hero": "幼馴染が攻略対象",
    "Adult Protagonist": "成人の主人公", "More Than Seven Endings": "エンディング8種以上",
    "Voiced Default Name": "デフォルト名を音声で呼ぶ", "Only a Single Hero": "攻略対象は1人のみ",
    "Only Adult Heroes": "攻略対象は全員成人", "Side Portraits": "立ち絵が横向き",
    "Yandere Hero": "ヤンデレの攻略対象", "Sexual Content": "性的描写あり", "Fantasy": "ファンタジー",
    "Modern Day Japan": "現代日本", "High School": "高校が舞台", "Student Hero": "学生の攻略対象",
    "Bad Ending(s)": "バッドエンドあり", "Protagonist with a Sprite": "主人公に立ち絵あり",
    "Shota Hero": "ショタの攻略対象", "Other Perspectives": "他視点パート",
    "Unlockable Routes": "解放式ルート", "Correct Choice Indicator": "正解選択肢の表示",
    "Bad Endings with Story": "物語のあるバッドエンド", "Tsundere Hero": "ツンデレの攻略対象",
    "Strong Female Protagonist": "芯の強い女性主人公", "White Haired Hero": "白髪の攻略対象",
    "Comedy": "コメディ", "Protagonist with Voice Acting": "主人公にボイスあり",
    "More Than Seven Heroes": "攻略対象8人以上", "Teacher Hero": "教師の攻略対象",
    "Ending List": "エンディング一覧機能", "Bonus Side Stories": "おまけシナリオ",
    "Oyaji Hero": "オヤジ系の攻略対象", "Music Recollection": "音楽鑑賞モード",
    "Photographic Backgrounds": "実写背景", "Lip Sync": "口パク同期",
    "Built-in Encyclopedia": "用語辞典搭載", "Under the Same Roof": "同居",
    "Map Movement": "マップ移動", "Unlockable Bonus Content": "解放式おまけ要素",
    "High School Student Hero": "高校生の攻略対象", "Drama": "ドラマ", "Bloody Scenes": "流血描写",
    "Branching Plot": "分岐する物語", "Normal Scene Recollection": "シーン回想",
    "Long Common Route": "共通ルートが長い", "Hero with a Sword": "剣を持つ攻略対象",
    "Brief NVL Scenes": "一部NVL形式", "Portrait Orientation": "縦画面",
    "Microtransactions": "課金要素", "Past Japan": "過去の日本", "Royal Hero": "王族の攻略対象",
    "Wealthy Hero": "富裕層の攻略対象", "Chosen Choices Marking": "既読選択肢の表示",
    "Backlog Jump": "バックログジャンプ", "Death of Hero": "攻略対象の死",
    "Sexual Innuendo": "性的な暗示", "Female Friend": "女友達",
    "Character Profiles": "キャラ紹介機能", "Fighting Hero": "戦う攻略対象",
    "Marriage Ending": "結婚エンド", "Multiple Route Mystery": "複数ルートで解ける謎",
    "Life and Death Drama": "生死を扱う物語", "Date Display": "日付表示",
    "Lots of Choices": "選択肢が多い", "Hero with Eyepatch": "眼帯の攻略対象",
    "Hero with Beauty Mark": "ほくろのある攻略対象", "Flirtatious Hero": "軽薄な攻略対象",
    "Relationship Chart": "相関図", "Varied Title Screens": "タイトル画面が変化",
    "Fan-fiction": "二次創作", "Hero Based on Real Person": "実在人物がモデルの攻略対象",
    "Enforced Playing Order": "攻略順の強制", "Magic": "魔法", "Mystery": "ミステリー",
    "Dark Skinned Hero": "褐色肌の攻略対象", "May-December Romance": "年の差恋愛",
    "Amnesia": "記憶喪失", "Japanese Mythology": "日本神話", "Flashback": "回想",
    "Knight Hero": "騎士の攻略対象", "Ponytail Hero": "ポニーテールの攻略対象",
    "One True End": "真エンドが1つ", "Protagonist's Senpai as a Hero": "先輩が攻略対象",
    "Colored Name-tags": "名前の色分け", "Princess Protagonist": "姫の主人公",
    "Demon Hero": "鬼・魔族の攻略対象", "Butler Hero": "執事の攻略対象",
    "Fast Mini-games": "短いミニゲーム", "Twin Brothers as Heroes": "双子の兄弟が攻略対象",
    "Kinetic Novel": "一本道（選択肢なし）", "Vampire Hero": "吸血鬼の攻略対象", "War": "戦争",
    "Fictional World": "架空世界", "Fighting Protagonist": "戦う主人公",
    "Orphan Protagonist": "孤児の主人公", "Kuudere Hero": "クーデレの攻略対象",
    "Protagonist's Non-blood-related Brother as a Hero": "義兄弟が攻略対象",
    "Multiple Protagonists": "主人公が複数", "Confinement": "監禁",
    "Past Setting in a Fictional World": "架空世界の過去", "Noble Hero": "貴族の攻略対象",
    "University Student Hero": "大学生の攻略対象", "Musician Hero": "音楽家の攻略対象",
    "Unlockable Hero(ine)": "解放式の攻略対象", "Time Travel": "タイムトラベル",
    "Non-human Hero": "人外の攻略対象", "Ponytail Protagonist": "ポニーテールの主人公",
    "Hero(ine) Selection": "攻略対象の選択制", "Sword Combat": "剣戟",
    "Western-style Manor": "洋館", "University Student Protagonist": "大学生の主人公",
    "Homicide": "殺人", "Horror": "ホラー", "Foreigner Hero": "外国人の攻略対象",
    "Slice of Life": "日常", "Villainous Hero": "悪役の攻略対象",
    "Medical Doctor Hero": "医師の攻略対象", "Death of Protagonist": "主人公の死",
    "Reincarnation": "転生", "Student Protagonist": "学生の主人公",
    "Jump to Next Choice": "次の選択肢へジャンプ",
    "NVL": "NVL形式", "Halloween": "ハロウィン", "The Holiday Season": "クリスマス・年末",
    "Scenario Selection": "シナリオ選択式", "Protagonist's Kouhai as a Hero": "後輩が攻略対象",
    "Protagonist's Side Image Toggle": "主人公立ち絵の表示切替",
    "Protagonist from a Different World": "異世界から来た主人公",
    "Valentine's Day": "バレンタイン", "Few Event CGs": "イベントCGが少ない",
    "Changeable Font": "フォント変更可", "Fairy Tale": "おとぎ話", "Hero in Kimono": "着物の攻略対象",
    "Simulation Game": "シミュレーション", "RPG": "RPG要素",
    "Protagonist's Brother as a Hero": "兄弟が攻略対象", "Summer": "夏",
    "Cheerful Hero": "明るい攻略対象", "Few Choices": "選択肢が少ない",
    "Soldier Hero": "軍人の攻略対象", "Protagonist in Relationship": "主人公に恋人がいる",
    "Ending Scene Recollection": "エンディング回想", "Super Deformed CGs": "デフォルメCG",
    "Loli Protagonist": "幼い主人公", "Completion Status Indicator": "達成率表示",
    "Kemonomimi Hero": "けものみみの攻略対象", "April Fool's": "エイプリルフール",
    "Idol Hero": "アイドルの攻略対象", "Ojousama Protagonist": "お嬢様の主人公",
    "Cafe": "カフェ", "Literary Adaptation": "文学作品が原作",
    "Unoriginal Soundtrack": "既製曲の使用", "Hero Based on a Fictional Person": "架空人物がモデルの攻略対象",
    "Donkan Protagonist": "鈍感な主人公", "Unlockable Choices": "解放式選択肢",
    "Polite Formal Hero": "敬語の攻略対象", "Built-in Walkthrough": "攻略ヒント搭載",
    "Mage Hero": "魔法使いの攻略対象", "Hero with Eye Covering Hairstyle": "目が隠れる髪の攻略対象",
    "Twin Tail Protagonist": "ツインテールの主人公", "Prince Hero": "王子の攻略対象",
    "Shinsengumi": "新選組", "Samurai Hero": "侍の攻略対象", "Bakumatsu Era": "幕末",
    "Edo Era": "江戸時代", "Rebellion": "反乱",
}

TRAIT_GROUP_JA = {
    "Hair": "髪", "Eyes": "瞳", "Body": "外見", "Clothes": "服装",
    "Personality": "性格", "Role": "役柄", "Engages in": "行動",
    "Subject of": "境遇", "Items": "持ち物",
}

TRAIT_JA = {
    "Hair > Short": "短髪", "Hair > Long": "長髪", "Hair > Brown": "茶髪", "Hair > Black": "黒髪",
    "Hair > Blond": "金髪", "Hair > Grey": "灰髪", "Hair > White": "白髪", "Hair > Blue": "青髪",
    "Hair > Red": "赤髪", "Hair > Violet": "紫髪", "Hair > Green": "緑髪", "Hair > Pink": "ピンク髪",
    "Hair > Orange": "オレンジ髪", "Hair > Multicolored": "多色の髪",
    "Hair > Shoulder-length": "肩までの髪", "Hair > Waist Length+": "腰までの髪",
    "Hair > Ponytail": "ポニーテール", "Hair > Straight": "ストレート", "Hair > Wavy": "ウェーブ",
    "Hair > Spiky": "逆立った髪", "Hair > Spiky Bangs": "尖った前髪", "Hair > V Bangs": "V字前髪",
    "Hair > Parted to Side": "横分け", "Hair > Parted in Middle": "中分け",
    "Hair > Curtained": "カーテン前髪", "Hair > Shaggy": "無造作ヘア",
    "Hair > Eye Covering": "目が隠れる髪", "Hair > Sidehair": "サイドヘア",
    "Eyes > Brown": "茶色の瞳", "Eyes > Blue": "青い瞳", "Eyes > Green": "緑の瞳",
    "Eyes > Amber": "琥珀色の瞳", "Eyes > Violet": "紫の瞳", "Eyes > Red": "赤い瞳",
    "Eyes > Black": "黒い瞳", "Eyes > Grey": "灰色の瞳", "Eyes > Pink": "ピンクの瞳",
    "Eyes > Hosome": "細目", "Eyes > Tareme": "たれ目", "Eyes > Tsurime": "つり目",
    "Body > Young-adult": "青年", "Body > Teen": "十代", "Body > Adult": "成人",
    "Body > Kid": "子ども", "Body > Pale": "色白", "Body > Olive": "褐色肌",
    "Body > Slim": "細身", "Body > Mole": "ほくろ", "Body > Kemonomimi": "けものみみ",
    "Body > Younger Appearance": "実年齢より幼い外見",
    "Clothes > School Uniform": "制服", "Clothes > Glasses": "眼鏡", "Clothes > Kimono": "着物",
    "Clothes > Suit": "スーツ", "Clothes > Shirt": "シャツ", "Clothes > Trousers": "ズボン",
    "Clothes > Necktie": "ネクタイ", "Clothes > Belt": "ベルト", "Clothes > Earrings": "ピアス",
    "Clothes > Gloves": "手袋", "Clothes > Vest": "ベスト", "Clothes > Jacket": "ジャケット",
    "Clothes > Blazer": "ブレザー", "Clothes > Coat": "コート", "Clothes > Cape": "マント",
    "Clothes > Dress": "ドレス", "Clothes > Boots": "ブーツ", "Clothes > Scarf": "マフラー",
    "Clothes > Cravat": "クラヴァット", "Clothes > Necklace": "ネックレス",
    "Clothes > Pendant Necklace": "ペンダント", "Clothes > Hairpin": "ヘアピン",
    "Personality > Kind": "優しい", "Personality > Friendly": "親しみやすい",
    "Personality > Mysterious": "謎めいた", "Personality > Serious": "真面目",
    "Personality > Refined": "上品", "Personality > Smart": "頭が良い",
    "Personality > Protective": "過保護", "Personality > Loyal": "忠実",
    "Personality > Stoic": "動じない", "Personality > Relaxed": "おっとり",
    "Personality > Hard Worker": "努力家", "Personality > Energetic": "元気",
    "Personality > Blunt": "無愛想", "Personality > Yandere": "ヤンデレ",
    "Personality > Tsundere": "ツンデレ", "Personality > Stubborn": "頑固",
    "Personality > Honest": "正直", "Personality > Reserved": "控えめ",
    "Personality > Confident": "自信家", "Personality > Taciturn": "無口",
    "Personality > Proactive": "積極的", "Personality > Arrogant": "傲慢",
    "Personality > Sharp-tongued": "毒舌",
    "Personality > Ore": "一人称「俺」", "Personality > Boku": "一人称「僕」",
    "Personality > Watashi": "一人称「私」",
    "Role > High School Student": "高校生", "Role > University Student": "大学生",
    "Role > Classmate": "同級生", "Role > Senpai": "先輩", "Role > Teacher": "教師",
    "Role > Childhood Friend": "幼馴染", "Role > Friend": "友人",
    "Role > Older Brother": "兄", "Role > Younger Brother": "弟",
    "Role > Twin Brother": "双子の兄弟", "Role > Father": "父親", "Role > Orphan": "孤児",
    "Role > Noble": "貴族", "Role > Prince": "王子", "Role > Wealthy": "裕福",
    "Role > Popular": "人気者", "Role > Antagonist": "敵役", "Role > Magician": "魔法使い",
    "Role > Nameable": "名前変更可", "Role > Based on a Real Person": "実在人物がモデル",
    "Role > Based on a Fictional Character": "架空人物がモデル",
    "Engages in > Fighting": "戦闘", "Engages in > Teasing": "からかう",
    "Engages in > Cooking": "料理", "Engages in > Flirting": "口説く",
    "Engages in > Murder": "殺人",
    "Items > Sword": "剣", "Items > Katana": "刀",
    "Subject of > Grief": "喪失・悲嘆", "Subject of > Death": "死",
    "Subject of > Confinement": "監禁される", "Subject of > Guilt": "罪悪感",
    "Role > Middle School Student": "中学生", "Role > Samurai": "侍", "Role > Kouhai": "後輩",
    "Role > Student": "学生", "Role > Knight": "騎士",
    "Body > Tall": "長身", "Body > Muscular": "筋肉質", "Body > Tattoo": "タトゥー",
    "Body > Androgynous": "中性的", "Body > Pointed Ears": "尖った耳",
    "Personality > Carefree": "気楽", "Personality > Strict": "厳格",
    "Personality > Cheerful": "明るい", "Personality > Womanizer": "女好き",
    "Personality > Outgoing": "社交的", "Personality > Mature": "大人びた",
    "Personality > Rude": "無礼", "Personality > Mischievous": "いたずら好き",
    "Personality > Naive": "純朴", "Personality > Short-tempered": "短気",
    "Personality > Sweets Lover": "甘い物好き",
    "Clothes > Hakama": "袴", "Clothes > Headband": "ヘアバンド",
    "Clothes > Ribbon Tie": "リボンタイ", "Clothes > Hat": "帽子",
    "Clothes > Choker": "チョーカー", "Clothes > Bracelet": "ブレスレット",
    "Clothes > Formal Shirt": "ドレスシャツ", "Clothes > Hoodie": "パーカー",
    "Clothes > Dress Shoes": "革靴", "Clothes > Decorative Belt": "装飾ベルト",
    "Clothes > Pendant Earrings": "垂れ下がるピアス", "Clothes > Knee-high Boots": "ニーハイブーツ",
    "Clothes > Ribbon Hair Tie": "リボンの髪飾り",
    "Hair > Blunt Bangs": "ぱっつん前髪", "Hair > Bob Cut": "ボブ", "Hair > Twin Tails": "ツインテール",
    "Hair > Ahoge": "アホ毛", "Hair > No Bangs": "前髪なし", "Hair > Braid": "三つ編み",
    "Eyes > Teal": "青緑の瞳", "Eyes > Cyan": "水色の瞳",
    "Engages in > Tennis": "テニス", "Engages in > Drinking": "飲酒",
    "Subject of > Teasing": "からかわれる",
}
